import { baseColors } from './colors';

export const darkTheme = {
  background: baseColors.gray900,
  card: baseColors.gray800,
  text: baseColors.gray50,
  textSecondary: baseColors.gray400,
  primary: baseColors.purple,
  primaryGradient: baseColors.gradientPrimary,
  success: baseColors.neonGreen,
  successGradient: baseColors.gradientSuccess,
  error: baseColors.red,
  errorGradient: baseColors.gradientError,
  border: baseColors.gray700,
  accent: baseColors.neonBlue,
  cryptoCard: baseColors.gray800,
  cryptoCardBorder: baseColors.gray700,
  priceUp: baseColors.neonGreen,
  priceDown: baseColors.red,
  marketCap: baseColors.neonBlue,
  volume: baseColors.purple,
  chartLine: baseColors.neonBlue,
  chartArea: 'rgba(0, 198, 255, 0.1)',
  tabBarActive: baseColors.neonBlue,
  tabBarInactive: baseColors.gray400,
};
