import { baseColors } from './colors';

export const lightTheme = {
  background: baseColors.gray50,
  card: baseColors.white,
  text: baseColors.gray900,
  textSecondary: baseColors.gray600,
  primary: baseColors.blue,
  primaryGradient: baseColors.gradientPrimary,
  success: baseColors.neonGreen,
  successGradient: baseColors.gradientSuccess,
  error: baseColors.red,
  errorGradient: baseColors.gradientError,
  border: baseColors.gray200,
  accent: baseColors.purple,
  cryptoCard: baseColors.white,
  cryptoCardBorder: baseColors.gray200,
  priceUp: baseColors.neonGreen,
  priceDown: baseColors.red,
  marketCap: baseColors.blue,
  volume: baseColors.purple,
  chartLine: baseColors.blue,
  chartArea: 'rgba(59, 130, 246, 0.1)',
  tabBarActive: baseColors.blue,
  tabBarInactive: baseColors.gray400,
  shadowColor: baseColors.shadowColor,
};
